import React, { useState } from 'react';
import { ArrowRight, RefreshCw, ChevronLeft } from 'lucide-react';
import { cn } from "@/lib/utils";
import { useNavigate } from 'react-router-dom';
import { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "@/components/ui/input-otp";

interface TwoFactorInlineProps {
    credentials: any;
    onVerify: (code: string) => void;
    onBackToLogin: () => void;
}

const TwoFactorFormInline = ({ credentials, onVerify, onBackToLogin }: TwoFactorInlineProps) => {
    const [code, setCode] = useState("");
    const [isVerifying, setIsVerifying] = useState(false);
    const navigate = useNavigate();

    const executeVerification = (verificationCode: string) => {
        setIsVerifying(true);
        setTimeout(() => {
            setIsVerifying(false);
            onVerify(verificationCode);
            navigate('/app');
        }, 1200);
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (code.length < 6 || isVerifying) return;
        executeVerification(code);
    };

    return (
        <form
            onSubmit={handleSubmit}
            className="flex flex-col border-x border-b border-zinc-300 bg-white font-mono"
        >
            {/* Context Notice Cell */}
            <div className="bg-zinc-50/50 p-4 border-b border-zinc-200 flex flex-col gap-1">
                <label className="text-[8px] font-black text-zinc-400 uppercase tracking-widest block leading-none">
                    MFA_CHALLENGE_VECTOR
                </label>
                <span className="text-[11px] font-bold text-zinc-900 uppercase tracking-tight mt-1">
                    Enter the token generated by your system authenticator.
                </span>
                {credentials?.email && (
                    <span className="text-[9px] text-zinc-400 lowercase mt-0.5">
                        Target handshake account: {credentials.email}
                    </span>
                )}
            </div>

            {/* OTP Slots Wrapper Block */}
            <div className="flex flex-col items-center justify-center py-8 px-4 border-b border-zinc-100">
                <InputOTP
                    maxLength={6}
                    value={code}
                    onChange={(val) => {
                        setCode(val);
                        if (val.length === 6 && !isVerifying) {
                            executeVerification(val);
                        }
                    }}
                >
                    <div className="flex items-center gap-1">
                        <InputOTPGroup>
                            <InputOTPSlot index={0} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                            <InputOTPSlot index={1} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                            <InputOTPSlot index={2} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                        </InputOTPGroup>

                        <InputOTPSeparator className="text-zinc-300 font-bold px-1" />

                        <InputOTPGroup>
                            <InputOTPSlot index={3} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                            <InputOTPSlot index={4} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                            <InputOTPSlot index={5} className="w-11 h-11 text-base font-black rounded-none border-zinc-300 bg-zinc-50 focus:bg-white focus:border-blue-600 focus:ring-0 transition-colors shadow-none" />
                        </InputOTPGroup>
                    </div>
                </InputOTP>
            </div>

            {/* Bottom Form Navigation Control Bar */}
            <div className="grid grid-cols-3 gap-0 border-t border-zinc-200">
                {/* Abort/Back button */}
                <button
                    type="button"
                    onClick={onBackToLogin}
                    className="h-11 bg-zinc-50 hover:bg-zinc-100 text-zinc-500 hover:text-zinc-900 border-none border-r border-zinc-200 text-[9px] font-black uppercase tracking-wider transition-colors flex items-center justify-center gap-1 cursor-pointer"
                >
                    <ChevronLeft size={12} className="mt-0.5" />
                    <span>Back</span>
                </button>

                {/* Submit button spans the remainder */}
                <button
                    type="submit"
                    disabled={isVerifying || code.length < 6}
                    className={cn(
                        "col-span-2 h-11 flex items-center justify-center gap-2 text-white transition-colors text-[9px] font-black uppercase tracking-[0.2em] border-none cursor-pointer",
                        isVerifying ? "bg-blue-600" : "bg-blue-600 hover:bg-blue-700 disabled:bg-zinc-100 disabled:text-zinc-300 disabled:cursor-not-allowed"
                    )}
                >
                    <span>{isVerifying ? "Verifying Token" : "Authorize Link"}</span>
                    {isVerifying ? <RefreshCw size={11} className="animate-spin" /> : <ArrowRight size={11} />}
                </button>
            </div>
        </form>
    );
};

export default TwoFactorFormInline;